#
# Makefile for the nfc tag fm19511 driver.
#

# Each configuration option enables a list of files.

obj-m += fmtag.o

fmtag-objs := fm19511.o

BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/fmtag.ko
